### ISSUE TITLE
Trim down article entries in index view

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/spaceduck#35]
I'd like to trim down the article entries so that it's a bit more minimal like mtlynch.io:

![image](https://user-images.githubusercontent.com/7783288/37868841-babd9abe-2f83-11e8-8e1f-b18870800ea9.png)

We can drop the excerpt and the "Continue reading" link line.

**Comment by shredtechular** [comment]
I know this issue is next in my queue, but going to wait for #67 to be merged before completing to minimize conflicts and maximize testing with both features.
