### ISSUE TITLE
Add htmlproofer to build

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/spaceduck#42]
Add an htmlproofer step to the build to match mtlynch.io (including support for the `--quick` flag.

**Comment by shredtechular** [comment]
I may have messed up identifying this issue properly to be closed in #52 as it contained 2 fixed issues.  Are we okay to manually close this issue?  I'm not able to do that on my end...

**Comment by mtlynch** [comment]
Oh yeah, I guess Github's issue linking didn't pick it up. Closing, thanks!
