### ISSUE TITLE
Suggestion + Question about Sia Load Test

### ISSUE THREAD

**Issue by RongxinZhang** [mtlynch/spaceduck#48]
Your load testing post on Sia was very insightful. Thank you. It provided quantitative data that the system is not as economic as they say on their website.

**Suggestion:**
It would be useful to have the load testing code modularized and open sourced. This way, we could create a performance monitoring service for Sia or Storj such that if network performance can be tracked over time e.g 1 month.

***Question:*
You stated in your blog post that`All uploads complete after 40 seconds.` Does this include the contract negotiation and creation time? Was this done through the API or the web interface?
https://blog.spaceduck.io/load-test-2/

**Comment by mtlynch** [comment]
>It would be useful to have the load testing code modularized and open sourced. This way, we could create a performance monitoring service for Sia or Storj such that if network performance can be tracked over time e.g 1 month.

Good news! All the code is already open-sourced and fully documented:

* [sia_load_tester](https://github.com/mtlynch/sia_load_tester): Drives the load tester by creating contracts with Sia, uploading files, and terminating when exit conditions are met.
* [sia_metrics_collector](https://github.com/mtlynch/sia_metrics_collector): Collects all Sia metrics at set intervals.

>You stated in your blog post that `All uploads complete after 40 seconds.` Does this include the contract negotiation and creation time? Was this done through the API or the web interface?

That was a hypothetical example to explain the nomenclature. It didn't describe something that happened during the test.

But for the statistics I report, bandwidth does not include the time spent creating the initial 50 contracts. Everything that the load tester does is through the Sia API.

**Comment by RongxinZhang** [comment]
@mtlynch Thank you for clearing that up and I'll take a look at the repos!
